export const emailKeywords: Record<string, number> = {
  "application for": 3,
  "job application": 3,
  "thanks for applying": 3,
  "thank you for applying": 3,
  "thanks for submitting": 3,
  "application has been received": 3,
  "application received": 3,
  "we received your application": 3,
  "application submitted": 3,
  "applying to": 3,
  "applying for": 3,
  "candidate for": 3,
  "attached my resume": 3,
  "attached my cv": 3,
  "cover letter": 3,
  "portfolio": 3,

  "interview": 2,
  "schedule interview": 2,
  "interview scheduled": 2,
  "interview time": 2,
  "interview confirmation": 2,
  "move forward": 2,
  "next round": 2,
  "phone screen": 2,
  "video interview": 2,
  "technical interview": 2,
  "meet the team": 2,
  "availability": 2,
  "confirm your availability": 2,

  "hiring process": 2,
  "next steps": 2,
  "position": 2,
  "role": 2,
  "opening": 2,
  "job opening": 2,
  "job description": 2,
  "job title": 2,
  "software engineer": 2,
  "recruiting": 2,
  "recruitment": 2,
  "recruitment process": 2,
  "job search": 2,
  "intern": 2,
  "internship": 2,
  "careers site": 2,
  "candidacy": 2,

  "offer letter": 2,
  "job offer": 2,
  "offer extended": 2,
  "congratulations": 2,
  "we're excited to offer": 2,
  "start date": 2,
  "onboarding": 2,
  "welcome to": 2,
  "salary": 2,
  "compensation": 2,
  "benefits": 2,

  "referral": 2,
  "referred by": 2,
  "hiring manager": 2,
  "recruiter": 2,
  "talent acquisition": 2,
  "hr": 2,
  "human resources": 2,
  "team would like": 2,
  "team is looking forward": 2,

  "experience": 1,
  "skills": 1,
  "qualifications": 1,
  "years of experience": 1,
  "background": 1,
  "expertise": 1,
  "requirement": 1,
  "requirement met": 1,

  "opportunity": 1,
  "career": 1,
  "professional": 1,
  "growth": 1,
  "development": 1,
  "new college grad": 1,
  "move forward with another candidate": 1,
  "careers page": 1,
  "careers": 1,

  "not moving forward": 1,
  "other candidate": 1,
  "position filled": 1,
  "better fit": 1,
  "thank you for your interest": 1,
  "no longer recruiting": 1,

  "unsubscribe": -5,
  "invoice": -5,
  "receipt": -5,
  "order": -5,
  "shipment": -5,
  "billing": -5,
  "account statement": -5,
  "transaction": -5,
  "purchase": -5,
  "credit card": -5,
  "daily cash": -5,
  "alarm": -5,
  "alert:": -5,

  "newsletter": -3,
  "promotion": -3,
  "promotional": -3,
  "marketing": -3,
  "promotional offer": -3,
  "job search hacks": -5,
  "growth hacker": -5,
  "bypass the gatekeepers": -5,
  "hireready": -5,
  "jobscan": -5,
}

export function sumKeywordMatches(text: string): number {
    const haystack = text.toLowerCase()
    let score = 0
    for (const [phrase, weight] of Object.entries(emailKeywords)) {
      if (haystack.includes(phrase.toLowerCase())) {
        score += weight
      }
    }
    return score
  }